name: procweb
version: git
summary: Command line monitoring tool
description: Command line monitoring tool

confinement: devmode
base: core22

apps:
  procweb:
    command: bin/procweb

parts:
  procweb:
    plugin: npm
    npm-node-version: 16.16.0
    npm-include-node: true
    source: .
    override-build: |
      npm install typescript -g
      npm i
      npm run build
      npm pack
    build-packages:
      - npm
      - cargo
    stage-packages:
      - libc6
      - libgcc1
      - libstdc++6