name: procweb
version: git
summary: Command line monitoring tool
description: Command line monitoring tool

confinement: devmode
base: core22

apps:
  procweb:
    command: bin/procweb

parts:
  procweb:
    plugin: npm
    npm-node-version: 16.16.0
    source: .
    build-packages:
      - npm
    stage-packages:
      - libc6
      - libgcc1
      - libstdc++6