name: procweb
version: git
summary: Command line monitoring tool
description: Command line monitoring tool

confinement: devmode
base: core22

apps:
  procweb:
    command: /usr/bin/

parts:
  qt:
    plugin: dump
    source: ""
    override-pull: |
      git clone git://code.qt.io/qt/qt5.git qt6
      cd qt6
      perl init-repository
    override-build: |
      cd qtbase
      ./configure --prefix /usr/Qt-amd64-6.4.0 --skip qtwebengine --skip qtdeclarative
      make -j20
      make install