name: Build
on: push

jobs:
    build:
        runs-on: ubuntu-22.04
        container:
            image: carlonluca/procweb-ci:latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                submodules: recursive
          - name: Build
            shell: bash
            run: |
                cd procweb-webui
                npm config set prefix '/root/.npm-global' -g
                npm config set cache '/root/.npm-cache' -g
                echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.profile
                source ~/.profile
                ./build.sh
                cd ..
                cd procweb-qt
                mkdir build
                cd build
                /opt/Qt-amd64-6.4.2/bin/qt-cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
                make
                make install DESTDIR=AppDir
                mkdir -p AppDir/usr/share/icons
                touch AppDir/usr/share/icons/test.png
                appimage-builder --recipe ../../appimage-builder/AppImageBuilder_x64.yml

    build-rust:
        runs-on: ubuntu-22.04
        container:
            image: carlonluca/procweb-ci-rust:resolute
        steps:
          - shell: Fix environment
            run: 'echo HOME=/home/sf | sudo tee -a $GITHUB_ENV'
          - name: Install git on container
            run: |
                apt update
                apt install -y git
          - name: Checkout
            uses: actions/checkout@v3
            with:
                submodules: recursive
          - name: Build
            shell: bash
            run: |
                export CROSS_CONTAINER_IN_CONTAINER=true
                export HOSTNAME=$(docker ps -ql)
                cd procweb-webui
                ./build.sh
                cd ..
                cd procweb-rust
                rm -f 386.js favicon.ico icon.svg index.html main.js polyfills.js runtime.js styles.css
                cp ../procweb-webui/dist/procweb-webui/* .
                cp ../icon.svg .
                rustup default stable
                cargo install cross
                . "$HOME/.cargo/env"
                cross build --release --target x86_64-unknown-linux-musl
                mkdir -p ../procweb-dist/x86_64-unknown-linux-musl
                mv target/x86_64-unknown-linux-musl/release/procweb-rust ../procweb-dist/x86_64-unknown-linux-musl/
                cargo clean
                cross build --release --target aarch64-unknown-linux-musl
                mkdir -p ../procweb-dist/aarch64-unknown-linux-musl
                mv target/aarch64-unknown-linux-musl/release/procweb-rust ../procweb-dist/aarch64-unknown-linux-musl/
                cargo clean
                cross build --release --target armv7-unknown-linux-musleabihf
                mkdir -p ../procweb-dist/armv7-unknown-linux-musleabihf
                mv target/armv7-unknown-linux-musleabihf/release/procweb-rust ../procweb-dist/armv7-unknown-linux-musleabihf/
          - name: Install xz
            run: |
                apt update
                apt install -y xz-utils
          - name: Compress artifacts
            shell: bash
            run: |
                set -e
                cd procweb-dist
                xz -9 -k x86_64-unknown-linux-musl/procweb-rust
                xz -9 -k aarch64-unknown-linux-musl/procweb-rust
                xz -9 -k armv7-unknown-linux-musleabihf/procweb-rust
          - name: Upload artifacts
            uses: actions/upload-artifact@v4
            with:
                name: procweb-rust
                path: |
                    procweb-dist/x86_64-unknown-linux-musl/procweb-rust.xz
                    procweb-dist/aarch64-unknown-linux-musl/procweb-rust.xz
                    procweb-dist/armv7-unknown-linux-musleabihf/procweb-rust.xz
                if-no-files-found: error